site_name: Cividi Handbook
site_url: https://handbook.cividi.ch/
site_description: A guide to our operations and platforms
site_author: Team Cividi

repo_url: https://github.com/cividi/handbook

copyright: Copyright &copy; 2020 <a href="https://cividi.ch">Cividi GmbH</a>.
site_name: Cividi Handbook
nav:
    - Home: index.md
    - About: about.md
theme:
    name: pulse

markdown_extensions:
    - toc:
        permalink: '#'

plugins:
    - search
