site_name: Cividi Handbook
site_url: https://handbook.cividi.ch/
site_description: A guide to our operations and platforms
site_author: Team Cividi

repo_url: https://github.com/cividi/handbook
repo_name: cividi/handbook

copyright: Copyright &copy; 2020 <a href="https://cividi.ch">Cividi GmbH</a>.
site_name: Cividi Handbook 0.2
nav:
  - 'Home':
      - 'Welcome':  'home/welcome.md'
      - 'Cividi': 'home/cividi.md'
      - 'Onboarding': 'home/onboarding.md'
  - 'Drafts':
      - 'About': 'drafts/about.md'
      - 'Your Draft': 'drafts/your_draft.md'
  - 'Tech Stack':
      - 'About': 'tech/about.md'
      - 'Snapshot': 'tech/snapshot.md'
      - 'Frictionless': 'tech/frictionless.md'
      - 'Orchestration & Data Pipelines': 'tech/pipelines.md'
      - 'Gemeindescan': 'tech/gemeindescan.md'
      - 'Lab': 'tech/lab.md'
  - 'Maps':
      - 'About': 'maps/about.md'
      - 'Maps': 'maps/maps_engine_performance_test.md'
      - 'Lab': 'maps.lab.md'
  - 'Style Guide':
      - 'About': 'styleguide/about.md'
  - 'Urbanism':
      - 'About': 'urbanism/about.md'
  - 'Projects':
      - 'About': 'projects/about.md'
  - 'Events': 
      - 'About': 'events/about.md'
      - 'GeoHackmin' : 'events/geohackmin.md'
  - 'Media':
      - 'About': 'media/about.md'

edit_uri: edit/main/docs/
theme:
  name: material 
  palette:
    - primary: deep purple
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.top
  icon:
    repo: fontawesome/brands/github
markdown_extensions:
    - toc:
        permalink: '#'
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
plugins:
    - search
    - git-revision-date
extra:
  version:
    provider: mike
